### ISSUE TITLE
not connect

### ISSUE THREAD

**Issue by SergeyBitpix** [nextcloud/integration_mastodon#7] opened 2020-10-05 08:28 UTC
Mastodon OAuth access token could not be obtained: E
https://@Redanarchyst@mastodon.ml

**Comment by eneiluj** [comment] 2020-10-05 08:30
> https://@Redanarchyst@mastodon.ml

Did you enter that as instance URL? If yes, that's wrong. You should use https://mastodon.ml . Any better?

**Comment by gruessung** [comment] 2020-10-07 06:17
Same issue with https://social.tchncs.de

**Comment by eneiluj** [comment] 2020-10-16 12:09
@SergeyBitpix

Are you sure you entered the instance URL in the "Mastodon instance address" field?

@gruessung I created an account on https://social.tchncs.de and was flawlessly able to authenticate with Nextcloud Mastodon integration.

Could you describe what you do and what happens exactly?

**Comment by gruessung** [comment] 2020-10-17 07:45
@eneiluj 
Here is a screencast: https://cloud.solardorf.eu/s/Zor6bQzty5WXp8P
NC error Log: https://paste.solardorf.eu/rehekibeyo.php

**Comment by eneiluj** [comment] 2020-10-18 15:41
Thanks for the details. We can deduce from your logs that some information is missing at the end of the OAuth handshake. It can be one of 4 things. I've just published v0.0.7 which produces more precise logs that will help us figuring out what went wrong. Could you try it and get the logs it produces?

Btw, I've enabled 2FA to see it this was causing the problem (and if I could reproduce it) and I'm still able to authenticate to https://social.tchncs.de . Weird stuff.

**Comment by gruessung** [comment] 2020-10-19 11:08
@eneiluj 
Error message: https://paste.solardorf.eu/relotafegu
Stacktrace: https://paste.solardorf.eu/usajaguyiq.shell

**Comment by eneiluj** [comment] 2020-10-19 12:11
Ok the error response from Mastodon is not very precise. It just says there is something wrong in the token request although every parameter seems to be sent correctly.

The only possible explanation is that the redirection URL generated on the server side is different from the one generated in your browser. This might be because you get rid of "index.php" in your Nextcloud config but then your browser still displays it.

Anyway I think it's fixed now. The redirection URL is always the same one: the one generated on server side.

Could you try v0.0.8 which I just released?

Thank you very much for your patience.

**Comment by gruessung** [comment] 2020-10-19 14:59
It works! Thanks :)

**Comment by eneiluj** [comment] 2020-10-19 15:13
Wow amazing. Nice bug hunting.

**Closed by eneiluj** 2020-10-19 15:13 UTC
